#!/usr/bin/make -f
# DSP-only LV2 build of MultiPlay 20/20 with DPF (git submodule) in ../../dpf
NAME = nhe-multiplay
FILES_DSP = MultiPlayPlugin.cpp
include ../../dpf/Makefile.plugins.mk
TARGETS = lv2_dsp
all: $(TARGETS)
